### Session

In [1]:
import tensorflow as tf

In [45]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

In [4]:
sess =  tf.Session()
b = tf.constant(5)
print(sess.run(b))

5


In [5]:
c = tf.constant(8)
with tf.Session() as sess : 
    print(sess.run(c))

8


### Constant

In [7]:
a = tf.constant(3)
b = tf.constant(3,tf.float32)
c = tf.constant([2,5,6,9,6])
d = tf.constant([[2,5,6],
                 [8,5,8],
                 [8,8,1]])
e = tf.constant('Start with TensorFlow')

In [8]:
with tf.Session() as sess : 
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))

3
3.0
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'Start with TensorFlow'


### Variable

In [9]:
a = tf.Variable(3)
b = tf.Variable(3,tf.float32)
c = tf.Variable([2,5,6,9,6])
d = tf.Variable([[2,5,6],[8,5,8], [8,8,1]])
e = tf.Variable('Start with TensorFlow')

In [10]:
with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print(sess.run(a))
    print(sess.run(b))
    print(sess.run(c))
    print(sess.run(d))
    print(sess.run(e))


3
3
[2 5 6 9 6]
[[2 5 6]
 [8 5 8]
 [8 8 1]]
b'Start with TensorFlow'


In [11]:
price = tf.Variable(20) 
sess = tf.Session()
init = tf.global_variables_initializer()
sess.run(init)
print('original price is : ',sess.run(price))

original price is :  20


In [12]:
price = tf.Variable(30) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(40) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(50) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

price = tf.Variable(60) 
sess.run(tf.global_variables_initializer())
print('the price is : ',sess.run(price))

the price is :  30
the price is :  40
the price is :  50
the price is :  60


In [13]:
price = tf.assign(price,50)
print('new price is : ',sess.run(price))

new price is :  50


In [14]:
for j in range(6) : 
    price = tf.assign(price,price+10)
    print('new price is : ',sess.run(price))

new price is :  60
new price is :  70
new price is :  80
new price is :  90
new price is :  100
new price is :  110


### Placeholder

In [15]:
a = tf.placeholder(tf.float32)
with tf.Session() as sess : 
    result = sess.run(a , feed_dict ={a:3})
    print(result)

3.0


In [16]:
a = tf.placeholder(tf.float32)
b = a*2
with tf.Session() as sess : 
    result = sess.run(b , feed_dict ={a:3})
    print(result)

6.0


In [17]:
x = tf.placeholder(tf.float32)
y = tf.placeholder(tf.float32)
z = tf.placeholder(tf.float32)
w = tf.placeholder(tf.float32)

b = x*2 + 3*y**4 - 4/z + w-9

with tf.Session() as sess : 
    result = sess.run(b , feed_dict ={x:3,y:4,z:8,w:6})
    print(result)

770.5


In [19]:
x = tf.placeholder(tf.float32)
y = x**2
with tf.Session() as sess :
    print(sess.run(y,feed_dict={x:5}))

25.0


In [20]:
x = tf.placeholder(tf.float32)
y = x**2
with tf.Session() as sess :
    print(sess.run(y, {x:[5,8,10,50]}))

[  25.   64.  100. 2500.]


In [21]:
x = tf.placeholder(tf.float32)
y = x**2
with tf.Session() as sess :
    print(sess.run(y, {x:list(range(5,100))}))

[  25.   36.   49.   64.   81.  100.  121.  144.  169.  196.  225.  256.
  289.  324.  361.  400.  441.  484.  529.  576.  625.  676.  729.  784.
  841.  900.  961. 1024. 1089. 1156. 1225. 1296. 1369. 1444. 1521. 1600.
 1681. 1764. 1849. 1936. 2025. 2116. 2209. 2304. 2401. 2500. 2601. 2704.
 2809. 2916. 3025. 3136. 3249. 3364. 3481. 3600. 3721. 3844. 3969. 4096.
 4225. 4356. 4489. 4624. 4761. 4900. 5041. 5184. 5329. 5476. 5625. 5776.
 5929. 6084. 6241. 6400. 6561. 6724. 6889. 7056. 7225. 7396. 7569. 7744.
 7921. 8100. 8281. 8464. 8649. 8836. 9025. 9216. 9409. 9604. 9801.]


In [22]:
w = tf.constant([5.0])
b = tf.Variable([7.0],tf.float32)

x = tf.placeholder(tf.float32)

LinearRegressionModel = w*x + b

with tf.Session() as sess :
    sess.run(tf.global_variables_initializer())
    print(sess.run(LinearRegressionModel,{x:[3,5,7,9]}))

[22. 32. 42. 52.]


### Operations

In [23]:
s1 = tf.constant('Hi, ')
s2 = tf.constant('people ')
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

b'Hi, people '


In [24]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

50


In [25]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.multiply(s1,s2)

sess = tf.Session()
print(sess.run(s3))

600


In [26]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.subtract(s1,s2)

sess = tf.Session()
print(sess.run(s3))

-10


In [27]:
s1 = tf.constant(20)
s2 = tf.constant(30)
s3 = tf.divide(s1,s2)

sess = tf.Session()
print(sess.run(s3))

0.6666666666666666


In [28]:
s1 = tf.constant(20)
s2 = tf.constant(3)
s3 = tf.pow(s1,s2)

sess = tf.Session()
print(sess.run(s3))

8000


In [29]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant(30)
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

[35 36 37 38]


In [30]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4])
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

[ 6  8 10 12]


In [31]:
s1 = tf.constant([5,6,7,8])
s2 = tf.constant([1,2,3,4,5,6,7])
s3 = tf.add(s1,s2)

sess = tf.Session()
print(sess.run(s3))

ValueError: Dimensions must be equal, but are 4 and 7 for '{{node Add_15}} = AddV2[T=DT_INT32](Const_31, Const_32)' with input shapes: [4], [7].

In [32]:
matrix1 = tf.constant([[5., 3.]])
matrix2 = tf.constant([[2.],
                       [2.]])
product = tf.matmul(matrix1, matrix2)

with tf.Session() as sess:
    result = sess.run(product)
    print (result)

[[16.]]


In [33]:
matrix1 = tf.constant([[5,6,9,8],
                      [1,2,8,9],
                      [7,9,5,6],
                      [1,2,3,9]])

In [34]:
matrix2 = tf.matrix_transpose(matrix1)

with tf.Session() as sess:
    result = sess.run(matrix2)
    print (result)

[[5 1 7 1]
 [6 2 9 2]
 [9 8 5 3]
 [8 9 6 9]]


### Graph

In [35]:
graph = tf.get_default_graph()

In [36]:
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [37]:
a= tf.constant(5)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [38]:
b= tf.constant(7)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [39]:
c= tf.add(a,b)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [40]:
d= tf.placeholder(tf.float32)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [41]:
e= tf.Variable(2)
graph.get_operations()

[<tf.Operation 'Const' type=Const>,
 <tf.Operation 'Const_1' type=Const>,
 <tf.Operation 'Const_2' type=Const>,
 <tf.Operation 'Const_3' type=Const>,
 <tf.Operation 'Const_4' type=Const>,
 <tf.Operation 'Const_5' type=Const>,
 <tf.Operation 'Const_6' type=Const>,
 <tf.Operation 'Const_7' type=Const>,
 <tf.Operation 'Const_8' type=Const>,
 <tf.Operation 'Const_9' type=Const>,
 <tf.Operation 'Const_10' type=Const>,
 <tf.Operation 'Const_11' type=Const>,
 <tf.Operation 'Variable/initial_value' type=Const>,
 <tf.Operation 'Variable' type=VariableV2>,
 <tf.Operation 'Variable/Assign' type=Assign>,
 <tf.Operation 'Variable/read' type=Identity>,
 <tf.Operation 'Variable_1/initial_value' type=Const>,
 <tf.Operation 'Variable_1' type=VariableV2>,
 <tf.Operation 'Variable_1/Assign' type=Assign>,
 <tf.Operation 'Variable_1/read' type=Identity>,
 <tf.Operation 'Variable_2/initial_value' type=Const>,
 <tf.Operation 'Variable_2' type=VariableV2>,
 <tf.Operation 'Variable_2/Assign' type=Assign>,
 <tf

In [42]:
for operation in graph.get_operations() :
    print(operation.name)

Const
Const_1
Const_2
Const_3
Const_4
Const_5
Const_6
Const_7
Const_8
Const_9
Const_10
Const_11
Variable/initial_value
Variable
Variable/Assign
Variable/read
Variable_1/initial_value
Variable_1
Variable_1/Assign
Variable_1/read
Variable_2/initial_value
Variable_2
Variable_2/Assign
Variable_2/read
Variable_3/initial_value
Variable_3
Variable_3/Assign
Variable_3/read
Variable_4/initial_value
Variable_4
Variable_4/Assign
Variable_4/read
init
Variable_5/initial_value
Variable_5
Variable_5/Assign
Variable_5/read
init_1
Variable_6/initial_value
Variable_6
Variable_6/Assign
Variable_6/read
init_2
Variable_7/initial_value
Variable_7
Variable_7/Assign
Variable_7/read
init_3
Variable_8/initial_value
Variable_8
Variable_8/Assign
Variable_8/read
init_4
Variable_9/initial_value
Variable_9
Variable_9/Assign
Variable_9/read
init_5
Assign/value
Assign
add/y
add
Assign_1
add_1/y
add_1
Assign_2
add_2/y
add_2
Assign_3
add_3/y
add_3
Assign_4
add_4/y
add_4
Assign_5
add_5/y
add_5
Assign_6
Placeholder
Placeh